const config = {
  COLOR_CORNFLOWER_BLUE: {
    r: 0.392,
    g: 0.584,
    b: 0.929,
    a: 1.0
  },
  WEBGL_UNSUPPORTED_ERR: 'Error initializing WebGL! Please esure your browser is compatible.',
  WEBGL_CREATION_ERR: 'Error creating WebGL device!',
  WEBGL_CANVAS_CONTEXT: 'webgl', // 'experimental-webgl',
  MOUSEBUTTON_LEFT_CLICK: 0,
  MOUSEBUTTON_RIGHT_CLICK: 2,
  MOUSTBUTTON_MOUSEWHEEL_CLICK: 1,
  GLOBAL_MIN_AMBIENT_LIGHT: 0.01,
  GLOBAL_MAX_AMBIENT_LIGHT: 0.99,

  // Default key bindings:
  ASCII_W: 87,
  ASCII_S: 83,
  ASCII_A: 65,
  ASCII_D: 68,
  ASCII_J: 74,
  ASCII_K: 75,
  ASCII_L: 76,
  ASCII_M: 77,
  ASCII_UP: 38,
  ASCII_DOWN: 40,
  ASCII_LEFT: 37,
  ASCII_RIGHT: 39,
  ASCII_SPACE: 32,
  ASCII_LSHIFT: 16,
  ASCII_ESCAPE: 27,
  ASCII_EQUALS: 61,
  ASCII_MINUS: 173, // ASCII Chart says this is 45, on my keyboard it's 173

  // Camera Actions:

  ROTATE_UP: 'ROTATE_UP',
  ROTATE_DOWN: 'ROTATE_DOWN',
  ROTATE_LEFT: 'ROTATE_LEFT',
  ROTATE_RIGHT: 'ROTATE_RIGHT',

  FORWARD: 'FORWARD',
  REVERSE: 'REVERSE',
  LEFT_STRAFE: 'LEFT_STRAFE',
  RIGHT_STRAFE: 'RIGHT_STRAFE',

  RAISE_CAM: 'RAISE_CAM',
  LOWER_CAM: 'LOWER_CAM',

  // General Actions:
  REFRESH: 'REFRESH',
  TESTACTION1: 'TESTACTION1',
  TESTACTION2: 'TESTACTION2',
  TESTACTION3: 'TESTACTION3',
  INCREMENT_VALUE: "INCREMENT_VALUE",
  DECREMENT_VALUE: "DECREMENT_VALUE",

  // Engine Actions:
  EXIT: 'EXIT',

  // Action types:
  CAMERA_ACTION: 'CAMERA_ACTION',
  GENERAL_KEYBINDING: 'GENERAL',
  ENGINE_KEYBINDS: 'ENGINE',
  HERO_BOUNDINGBOX_XRADIUS: 0.20,
  HERO_BOUNDINGBOX_YRADIUS: 0.20,
  HERO_BOUNDINGBOX_ZRADIUS: 0.20,

  BATTLE_RUN_DEBOUNCE_FRAME_MAX: 120,
  BATTLE_RUN_DEBOUNCE_FLICKER_DIVISOR: 10,
  BATTLE_RUN_DEBOUNCE_FLICKER_TARGET: 5,
  GAME_TICKS_PER_SECOND: 60

};

export default { config };
